name: Safe Python images

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Python 3.12"
            dockerfile: "./python/python-3-12-slim.dockerfile"
            tags: "safe-image:python-3.12"
            platforms: "linux/amd64,linux/arm64"
          - name: "Python 3.13"
            dockerfile: "./python/python-3-13-slim.dockerfile"
            tags: "safe-image:python-3.13"
            platforms: "linux/amd64,linux/arm64"
         
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push ${{ matrix.name }} Image
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ secrets.DOCKER_USER }}/${{ matrix.tags }}
          push: true
          context: .
