name: Safe RabbitMQ images

on:
  push:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "RabbitMQ Management 3"
            dockerfile: "./rabbitmq/rabbitmq-3-management.dockerfile"
            tags: "safe-image:rabbit-3-management"
            platforms: "linux/amd64,linux/arm64"
          - name: "RabbitMQ Management 4"
            dockerfile: "./rabbitmq/rabbitmq-4-management.dockerfile"
            tags: "safe-image:rabbit-4-management"
            platforms: "linux/amd64,linux/arm64"
          - name: "RabbitMQ Management Latest"
            dockerfile: "./rabbitmq/rabbitmq-latest.dockerfile"
            tags: "safe-image:rabbit-latest"
            platforms: "linux/amd64,linux/arm64"
         
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push ${{ matrix.name }} Image
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          tags: ${{ secrets.DOCKER_USER }}/${{ matrix.tags }}
          push: true
          context: .
